2020-05-29 01:10:48,223 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 97, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2020-05-29 01:11:45,382 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:12:18,573 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:12:30,451 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 99, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\AskWall\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\HP\Desktop\AskWall\app\models.py", line 61, in get_reset_password_token
    return jwt.encode(
NameError: name 'jwt' is not defined
2020-05-29 01:13:21,802 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:13:34,807 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 99, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\AskWall\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\HP\Desktop\AskWall\app\models.py", line 63, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'time' is not defined
2020-05-29 01:14:27,812 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:14:37,769 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 99, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\AskWall\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\HP\Desktop\AskWall\app\models.py", line 64, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
TypeError: 'module' object is not callable
2020-05-29 01:15:13,531 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:15:22,925 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 99, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\AskWall\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\HP\Desktop\AskWall\app\models.py", line 65, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2020-05-29 01:16:01,901 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
