2020-05-30 15:51:41,357 ERROR: Exception on /u [GET] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 137, in u
    return render_template('404.html')
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 34, in top-level template code
    <a href="{{ url_for('user', username=current_user.username) }}">Profile</a>
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'register' instead?
2020-05-30 15:52:11,812 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:49]
2020-05-30 15:52:14,156 ERROR: Exception on /u [GET] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 137, in u
    return render_template('404.html')
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 34, in top-level template code
    <a href="{{ url_for('user', username=current_user.username) }}">Profile</a>
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'register' instead?
2020-05-30 15:52:46,695 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:49]
2020-05-30 15:52:56,658 ERROR: Exception on /person [GET] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 137, in person
    return render_template('404.html')
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 34, in top-level template code
    <a href="{{ url_for('user', username=current_user.username) }}">Profile</a>
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'register' instead?
